name: evolve_api
description: API for Evolve MMA booking system
version: 1.0.0

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
